name: Arrakis
version: '${project.version}'
main: rezcom.arrakis.Main
api-version: 1.18
commands:
  giveartifact:
    description: Gives an artifact of choice.
    usage: /giveartifact <artifact name>
    permission: arrakis.giveartifact
  lessersoulmob:
    description: Spawns a powerful foe with a Bene Gesserit Stylus
    usage: /lessersoulmob
    permission: arrakis.gesseritmob