name: Arrakis
version: '${project.version}'
main: rezcom.arrakis.Main
api-version: 1.18
commands:
  stillsuit:
    description: Gives a stillsuit to the player who calls this command.
    usage: /stillsuit
    permission: arrakis.stillsuit.give
  muaddibcharm:
    description: Gives a charm to the player who calls this command
    usage: /muaddibcharm
    permission: arrakis.charm.give